### ISSUE TITLE
Feature Request: New "Outcome" component

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme#26]
We’d like there to be: Entities, Processes, and Outcomes. Entity is the new name for Components, Process is new name for Mechanism, and Outcome is the new “thing.” Outcome can behave same as Entity in that it can host a property, connects via a process, etc. The differences would be:
1) the color
2) the shape (if easy) - just something slight to help it stand out
3) the help text 

Ideally, if you can make it easy to change the label (Entity, Process, Outcome) in the code or a template file, as well as the help text, that’d be great in case we continue to debate, but I think we are set.

---

## Tasks

* [x]  Rename "Components" to "Entities"
* [x]  Rename "Mechanism" to "Process"

---

* [x]  Add new "Outcome" object
* [x]  Outcomes have a different color
* [x]  Outcomes have a different shape
* [x]  Outcomes are referenced in help text
* [x]  Outcomes are listed separately in ToolsPanel
* [x]  Outcomes are listed first in ToolsPanel
* [x]  Outcome Link Buttons have a different color

---

* [x]  Labels for all objects are implemented via template file
* [x]  PropDialog and MechDialog use new names for:
* [x]  -- Open Dialog buttons
* [x]  -- Dialog prompt text
* [x]  -- Help Text
* [x]  "Add Property" should add same propType as parent.
* [x]  DescriptionView hover popup dialog needs to match propType color.

---

* [x]  Add border to ToolPanel entries to prevent shifting during hover

---

* [x]  Differentiate datamap naming from database ids.

---

QA / BUGS

* [x]  Verify that saves to db with electron app work
* [x]  Verify that old project data can be loaded and displayed
* [x]  ToolsPanel button colors are not using DEFAULTS
* [x]  PropsDialog is displaying ids not labels
* [x]  Adding a comment to a subprop does not resize parent prop
* [x]  MechDialog needs to account for propType.
* [x]  `ur-link.js:314 Uncaught (in promise) dbids must be array of ints` ur-link.js:314 -- related to LinkButton
* [x]  `Click on target` button sized too large in MechDialog
* [x]  ToolsPanel prop/outcome item hovers do not set background color
---

**Comment by benloh** [comment]
marked the checklist item **-- Dialog prompt text** as completed

**Comment by benloh** [comment]
marked the checklist item **Outcomes are listed first in ToolsPanel** as completed

**Comment by benloh** [comment]
marked the checklist item **Outcomes are listed separately in ToolsPanel** as completed

**Comment by benloh** [comment]
marked the checklist item **Outcomes have a different shape** as completed

**Comment by benloh** [comment]
marked the checklist item **Outcomes have a different color** as completed

**Comment by benloh** [comment]
marked the checklist item **Add new "Outcome" object** as completed

**Comment by benloh** [comment]
@jdanish Here's a rough first pass implementation of Outcomes.

![screenshot_736](https://github-attachments-inquirium.s3.amazonaws.com/659921876/52c3b6a2242e5bed59b0a441f4259424c1d3c8912806b4c08e7c4b02143198c6/screenshot_736.png)

You can try it out on branch `outcome`, which I just pushed to the server.

Features:

* Outcomes are displayed as a pink/purple rounded rectangle.
* Processes can point to any Outcome or nested Outcome.
* Outcomes can be nested in either an Outcome or an Entity
* There's a new "OUTCOME" section in the ToolsPanel.
* You can click the (+) button to add a new Outcome
* The PropDialog now references the type (e.g. Outcome or Entity)
* The type is defined centrally (see `boilerplate/src/system/common-datamap.js`)


A few questions:

1. Is the visual different enough?  It's easy enough to change the color, but we wanted to reserve greenish tint for the evidence and reddish for alerts, and orange is already used by process.  We can also easily play with the radius of the rounded rectangle.  We thought making it extra round would emphasize the difference.

1. We're not doing any kind of parent-child checking and assuming that any object (outcome or entity) can be nested inside of the other.  Is this what you want?

1. If you select an Outcome and click "Add Property" should the property that is added be an Outcome or an Entity?

1. I assume it's OK to reduce the size of the (+) "Add Outcome/etc" buttons in the ToolsPanel to save vertical space?

1. Do you want "Outcomes" listed first?  (You had mentioned this in passing in an email.  It's easy enough to change).

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 25, 2020, 14:53

Awesome!! I need to run some of this past the team, but:
1.  The visual difference is plenty I think. My instinct is to switch it so that components are rounded and outcomes are square. I assume that isn't too big of a deal? I'll check with the team on the color. The other thing that occurred to me is that we could make the "outcome" have a border to help convey that it is an outcome, but I think the shape and color are enough. So, I'll confirm flipping the shapes and a new color (or keeping that one) if that's cool?
2. I agree anything can be nested anywhere. We'll handle that socially if it seems weird.
3. I think the "add property" should create the same time as the parent. If you really want the other one you can make it separately and drag it over. Long-term we might want a convert option but I think it isn't worth it right now.
4. Absolutely OK to reduce the size of the (+) buttons. Would it be bad to make them pill buttons that just say "add process" etc and drop the +?  That might be easier and more consistent, but if its a hassle then smaller + is AOK.
5. I think Outcomes first as-is is AOK.
6. I noticed a possible bug - I created an outcome with an identical name to a component and then deleted the component. Then when I linked evidence to that outcome, it changed shape to be a component. However, when I made a new outcome with a slightly different name all worked as expected. Seems like a rare thing, but ... since it happened I figured I'd note it.

Otherwise. I assume that the names will change in help and in the mechanism/process edit panel, etc? Will the color of the links in the mechanism editor also change? Not crucial but would be consistent.

I'll send this along today and see what everyone thinks. But I think it looks great! Thanks!

Joshua

**Comment by benloh** [comment]
@jdanish Thanks!

Re 1. An outline would interfere with the Process line pointing to any sub-properties.  Also, we already use outlines to indicate an object is selected.  I'd prefer to avoid the outline if possible.  Easy enough to change the rounded between components. 

Re 4. I'm revamping the whole ToolsPanel.  Increasing it by about 10 px is giving it a lot more breathing room.  I'm renaming and tightening up the overall layout.

Re 6. Interesting bug.  I haven't been able to reproduce it.  Can you give me exact step-by-step instructions to do that?  We should be properly using unique ids now for all objects, but it's always possible something slipped through the cracks.

The color of the Link buttons in the Mechanism Dialog as well as the Evidence Links will change...I just haven't gotten to it yet.  The challenge is going to be managing all the exceptions and changes in a clean manner.

**Comment by benloh** [comment]
marked the checklist item **Add border to ToolPanel entries to prevent shifting during hover** as completed

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 25, 2020, 17:26

Yeah, that makes sense re: the outline.

Let’s go ahead and swap the shapes when you get a chance.

Weirdly, I cannot recreate the bug now. Could it be due to old data? Or is this backwards compatible?  It seems to be …  I’ll keep trying but if it doesn’t happen again, oh well!

Joshua

**Comment by benloh** [comment]
@jdanish Here's a pass at that:
* Outcomes are now square, props rounded.
* Gray is going to be easy to confuse with the light indigo prop color, so I gave it a red-tinged gray.

![screenshot_737](https://github-attachments-inquirium.s3.amazonaws.com/659921876/0f3fc13c4e64e8f3c740ad63c1410005550c88fa2d6ddf0ef695a2f3b712da9b/screenshot_737.png)

Note that the toolspanel would also reflect the gray, so we'd end up with a big fat gray button, which I'm not crazy about.  We can try pushing the color closer to purple so it doesn't have the red connotations.  We could also try cyan and/or push the prop indigo towards blue to better differentiate it.

Here's the whole screen with the cleaned up ToolsPanel -- note the purple Outcomes button will need to be changed to match whatever color we end up with:

![screenshot_740](https://github-attachments-inquirium.s3.amazonaws.com/659921876/95bae540c82842bc42aeafb85aedbab50eefe04cd6b58006b2e8b28f1d7b1f25/screenshot_740.png)

Here's cyan, which feels too light:

![screenshot_739](https://github-attachments-inquirium.s3.amazonaws.com/659921876/0f307808a80abc4724f5d683512c115cfbd29161b2253b79a2cd677a76384c5b/screenshot_739.png)

Here's blue, which I like better:

![screenshot_738](https://github-attachments-inquirium.s3.amazonaws.com/659921876/9fe09395d7a6a7a4d35020015d79d43408bad0485ffb8412db150ad567f2181c/screenshot_738.png)

**Comment by benloh** [comment]
marked the checklist item **-- Open Dialog buttons** as completed

**Comment by benloh** [comment]
marked the checklist item **"Add Property" should add same propType as parent.** as completed

**Comment by benloh** [comment]
marked the checklist item **PropDialog and MechDialog use new names for:** as completed

**Comment by benloh** [comment]
marked the checklist item **Labels for all objects are implemented via template file** as completed

**Comment by benloh** [comment]
marked the checklist item **-- Help Text** as completed

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 27, 2020, 15:06


Thanks @benloh ! The shapes look great, thanks! Kalani (my color expert) voted we go dark with white text, but that obviously won't work with the way you are doing transparency. I take your point on the gray button...

Looking here: https://davidmathlogic.com/colorblind/#'Reference to deleted milestone 23'D81B60-'Reference to deleted milestone 231'E88E5-'Reference to deleted milestone 23'FFC107-'Reference to deleted milestone 23004'D40 to make sure we are color-blind friendly ...  (see attached for which image to look at) ![Screen_Shot_2020-04-27_at_5.55.07_PM](https://github-attachments-inquirium.s3.amazonaws.com/659921876/e75b88f251ae568608ea07d1f370cd9e9b1e8d2896a25683ede645b1e7a522b0/Screen_Shot_2020-04-27_at_5.55.07_PM.jpeg)...

What about the Blue (Entities) and Purple (Outcomes) of the IBM pallette? Those look like they'd be clear and unproblematic? So a bit lighter on the blue from  your final example, and a bit more purple, but reversed in terms of blue on Entities and Purple on Outcomes. How's that look?  Am I right in assuming that this is something I can change easily in one place later so that we could go with those colors and I can tweak it later rather than eating up your time?

Oh, and super minor thing, but could we change the category labels in the toolbar to be plural? So Outcomes, Add Outcome. Etc.

Thanks!!

**Comment by benloh** [comment]
marked the checklist item **Outcomes are referenced in help text** as completed

**Comment by benloh** [comment]
marked the checklist item **Rename "Mechanism" to "Process"** as completed

**Comment by benloh** [comment]
marked the checklist item **Rename "Components" to "Entities"** as completed

**Comment by benloh** [comment]
@jdanish 

I can tweak the colors toward the IBM range, but keeping in mind we are using MUI theme colors for a lot of the basic widgets.  So there's probably a limit to how far we want to go with that: https://material-ui.com/customization/color/

You're welcome to tweak colors.  But they are a little scattered. I can try to clean up as we go, but a lot of the colors got wired in while we were prototyping, so they're split between some centralized colors, colors defined in css, and colors defined in code.

The big issue is probably that we're using transparency in the basic model objects, so solid colors won't work, at least not easily and not without a fair amount of rewriting (e.g. we're relying on transparency to show embeddedness...if they're solid we'd have to figure out a different way to show sub properties).

Re plurals...So is "Entitys" OK?  Or should it be "Entities"?  We'd have to add a special "plural" datamap object if you needed it to be correct.

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 27, 2020, 15:41

Thanks @benloh 

Cool. Let’s try with those colors and figure it out later if they don’t work.

No worries about cleaning it up - if we need to change it I can find then no problem. I’d rather prioritize some of the other things with our dwindling funds (though we are already planning on submitting a follow up!!).

As for plural - if it’s easy to include that to do it right, great. If it’s a lot of work (more than an hour?) let’s leave it singular.

Thanks,

Joshua

**Comment by benloh** [comment]
@jdanish Better?

![screenshot_741](https://github-attachments-inquirium.s3.amazonaws.com/659921876/32df50ee13da859cd2cec9a104b39b0aee5bb0f707572a1208b202c272607553/screenshot_741.png)

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 27, 2020, 16:05

@benloh I like it! Let’s run with that. I’ll get the team’s OK but think that’s great for now. Thanks!!

**Comment by benloh** [comment]
marked the checklist item **Differentiate datamap naming from database ids.** as completed

**Comment by benloh** [comment]
marked the checklist item **Object hover popup dialog needs to match propType color.** as completed

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 29, 2020, 06:31

@benloh we can go ahead with those colors for now. Thanks!!

**Comment by benloh** [comment]
marked the checklist item **Outcome Link Buttons have a different color** as completed

**Comment by benloh** [comment]
@jdanish I believe the Outcomes addition is now feature complete.  I'm moving to QA testing now to make sure everything works.  The latest changes have been pushed to the `outcome` branch, so please give it a final spin and let me know if you want anything changed.

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 29, 2020, 14:22

@benloh Looking good so far. As I mentioned in email, I am seeing some funny activity on old items, but let's ignore those as that won't be an issue moving forward. I think.

Two other minor things:
* [ ] The process edit panel shows outcomes as blue not purple
* [ ] Outcomes within Mechanisms or Mechanisms within Outcomes aren't marked as different in any way. Would it be easy to flip the color? If it's not, let's ignore it as not a big deal.

**Comment by benloh** [comment]
Good catch.

I'm not sure what you mean by "Outcomes within Mechanisms or Mechanisms within Outcomes aren't marked as different in any way"?  Are you referring tot he Process Edit Panel?

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 29, 2020, 14:36

Sorry, referring to the tool panel. If we are being 100% consistent, a property on an outcome would be blue. I am not sure it really matters, but if its easy….

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 29, 2020, 14:43

@benloh Also, the purple in the toolpanel looks lighter than that in the actual outcomes within the model and the popup for details. Can we match them? If this is just the setting playing out (i.e., it would require an exception) then ignore me.

**Comment by benloh** [comment]
Thanks.  I had forgotten that I was going to revisit the ToolsPanel colors after we confirmed the color choices.  They should now match the color of the DescriptionView popup (when you hover over the object).

**Comment by benloh** [comment]
In GitLab by @jdanish on Apr 29, 2020, 14:56

Cool.

**Comment by benloh** [comment]
marked the checklist item **ToolsPanel button colors are not using DEFAULTS** as completed

**Comment by benloh** [comment]
marked the checklist item **PropsDialog is displaying ids not labels** as completed

**Comment by benloh** [comment]
marked the checklist item **MechDialog needs to account for propType.** as completed

**Comment by benloh** [comment]
marked the checklist item **MechDialog needs to account for propType.** as incomplete

**Comment by benloh** [comment]
marked the checklist item **MechDialog needs to account for propType.** as completed

**Comment by benloh** [comment]
marked the checklist item **Adding a comment to a subprop does not resize parent prop** as completed

**Comment by benloh** [comment]
marked the checklist item **`Click on target` button sized too large in MechDialog** as completed

**Comment by benloh** [comment]
marked the checklist item **ToolsPanel prop/outcome item hovers do not set background color** as completed

**Comment by benloh** [comment]
marked the checklist item **`ur-link.js:314 Uncaught (in promise) dbids must be array of ints` ur-link.js:314 -- related to LinkButton** as completed

**Comment by benloh** [comment]
marked the checklist item **Verify that saves to db with electron app work** as completed

**Comment by benloh** [comment]
marked the checklist item **Verify that old project data can be loaded and displayed** as completed

**Comment by benloh** [comment]
closed
