### ISSUE TITLE
Other Fall 2020 Wishlist items

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme#41]
In GitLab by @jdanish on Aug 28, 2020, 07:30

Assuming we have time after duplicating models:
* [x] Deleting models -- see #40
* [x] Adding a check-box to fade model elements as a way of indicating they might get deleted / they are not yet confirmed -- see #51
* [x] Check-box to make arrows on processes bi-directional or uni-directional (not with those words, maybe a both ways or only one way option and hide the reverse if it is both-ways selected)
* [x] Sort model list by update (or name) -- see #55
* [x] Delete resources -- see #56
* [x] Process editing bug 
* [x] Make process definition text a bit easier to read (slightly bigger / less faded?) -- see #57

@benloh I am just sticking these here for now so I don't forget, but we are hoping we can sneak some of these in once that funding is approved. Thanks!

**Comment by benloh** [comment]
Got it!

**Comment by benloh** [comment]
In GitLab by @jdanish on Sep 17, 2020, 07:58

Revised original note to update priority list. Though we can revisit once the key item (duplicating and re-assigning models) is complete and see how time is looking / check what folks think.

**Comment by benloh** [comment]
marked the checklist item **Deleting models -- see #40** as completed

**Comment by benloh** [comment]
marked the checklist item **Adding a check-box to fade model elements as a way of indicating they might get deleted / they are not yet confirmed -- see #51** as completed

**Comment by benloh** [comment]
marked the checklist item **Check-box to make arrows on processes bi-directional or uni-directional (not with those words, maybe a both ways or only one way option and hide the reverse if it is both-ways selected)** as completed

**Comment by benloh** [comment]
In GitLab by @jdanish on Oct 23, 2020, 06:49

marked the checklist item **Process editing bug** as completed

**Comment by benloh** [comment]
In GitLab by @jdanish on Oct 23, 2020, 06:50

Edited to check off the process-editing bug since that was closed, and add a minor visual item to the bottom of the list. Time permitting - that's an easy one for me to do if needed.

**Comment by benloh** [comment]
@jdanish thanks!  By the way you can go here https://gitlab.com/inq-seeds/boilerplate/-/milestones/1 (On the sidebar click "Issues" > "Milestones" > "Fall 2020 Extension" and on the right sidebar you'll see a time tracking bar.  It should be pretty close to accurate as I update it every day.  I'm trying to do this all in GitLab instead of having a separate Trello list.  It's not quite as easy to read as Trello, but it's nice having it all in one place.

The "Boards" view is also helpful, more like Trello's Kanban. https://gitlab.com/inq-seeds/boilerplate/-/boards

**Comment by benloh** [comment]
In GitLab by @jdanish on Oct 23, 2020, 10:18

Thanks! I’ve been glancing at that. One thing I wasn’t sure of - is that your estimate of how long it would all take, or the budget that is at the max end? Not sure it matters yet, but trying to make sure I know how to read it.

Thanks,

**Comment by benloh** [comment]
Ah, yeah that would've been helpful to explain: I was using "estimate" as the actual budget.  GitLab doesn't seem to have a budget feature.  This seemed handy.  We might decide in the future that we actually need to use the estimate field properly.  But for now I figured it was a useful shorthand.

We're also supposed to have a burndown chart, but GitLab screwed up our renewal, so some features are locked at the moment.

**Comment by benloh** [comment]
marked the checklist item **Delete resources -- see #56** as completed

**Comment by benloh** [comment]
marked the checklist item **Make process definition text a bit easier to read (slightly bigger / less faded?) -- see #57** as completed
